version: 0.2

env:
  # varabile: "BUILD_ENV" from pipeline
  parameter-store:
    GITHUB_USER: "/github.com/finatext/cicd-user"
    GITHUB_TOKEN: "/github.com/finatext/cicd-token"

phases:
  install:
    runtime-versions:
      docker: 18



  pre_build:
    commands:
      - docker login ghcr.io -u "${GITHUB_USER}" -p "${GITHUB_TOKEN}"
      - |
        docker run --rm -v $(pwd):/work -w /work \
          ghcr.io/finatext/docker-images/node:12.13.1 \
          yarn install
  build:
    commands:
      - |
        docker run --rm -v $(pwd):/work -w /work \
          ghcr.io/finatext/docker-images/node:12.13.1 \
          yarn build:${BUILD_ENV}
artifacts:
  files:
    - '**/*'